server:
  port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    platform: postgres
    url: jdbc:postgresql://db:5432/database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://db:5432/database
    user: user
    password: password